version: '3'

services:
  training:
    build: ./training
    container_name: kurkkumopotin-training
    volumes:
      - model:/src/model
      - imgs:/src/imgs
      - ./kurkkumopotin/training/data:/src/data
  client:
    build: ./client
    ports:
      - 3000:3000
    restart: unless-stopped
    container_name: kurkkumopotin-client
  server:
    build: ./server
    ports:
      - 5000:5000
    restart: unless-stopped
    container_name: kurkkumopotin-server
    volumes:
      - model:/src/model
volumes:
  model:
  imgs:
