kind: Service
apiVersion: v1
metadata:
  labels:
    app: kurkkumopotin
  name: kurkkumopotin
  namespace: workshop

spec:
  type: LoadBalancer
  ports:
    - name: client
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: kurkkumopotin