kind: Service
apiVersion: v1
metadata:
  labels:
    app: kurkkumopotin
  name: kurkkumopotin
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: client
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: backend
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: kurkkumopotin